# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JX3_tosTb0hcTr5yLjqh4XgpDhVkhD89
"""

from flask import Flask, request, jsonify
import joblib
import pandas as pd
import os

app = Flask(__name__)

# Load pipeline and expected column names
pipeline = joblib.load("loan_pipeline.pkl")
#expected_columns = joblib.load("pipeline_columns.pkl")  # saved this during training

@app.route('/')
def home():
    return "🏡 Loan Approval Prediction API is running!"

@app.route("/predict", methods=["POST"])
def predict():
    try:
        data = request.get_json()
        df = pd.DataFrame([data])  # Keep this!
        prediction = pipeline.predict(df)
        return jsonify({"prediction": int(prediction[0])})
    except Exception as e:
        return jsonify({"error": str(e)})

if __name__ == "__main__":
    app.run(debug=True)