# -*- coding: utf-8 -*-
"""app_streamlite.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11PeXC4FFrA0rlF2V6vaRFoV-CbxPER0n
"""

# 📄 app.py

import streamlit as st
import joblib
import numpy as np
import pandas as pd

# Load the full pipeline
pipeline = joblib.load("loan_pipeline.pkl")

st.title("🏦 Loan Approval Prediction App")
st.markdown("🔍 Enter loan application details:")

# Input Fields
person_age = st.number_input("👤 Age", min_value=18, max_value=100, value=30)
person_gender = st.selectbox("👩‍🦰 Gender", ["female", "male"])
person_education = st.selectbox("🎓 Education", ['Master', 'High School', 'Bachelor', 'Associate', 'Doctorate', "Other"])
person_income = st.number_input("💰 Income", min_value=0.0, step=1000.0)
person_emp_exp = st.number_input("📊 Employment Experience (Years)", min_value=0, max_value=50)
person_home_ownership = st.selectbox("🏠 Home Ownership", ["RENT", "OWN", "MORTGAGE", "OTHER"])

loan_amnt = st.number_input("💸 Loan Amount", min_value=1000.0, step=1000.0)
loan_intent = st.selectbox("📄 Loan Intent", ["EDUCATION", "MEDICAL", "VENTURE", "PERSONAL", "HOMEIMPROVEMENT", "DEBTCONSOLIDATION"])
loan_int_rate = st.number_input("📈 Interest Rate (%)", min_value=0.0, max_value=100.0, step=0.1)
loan_percent_income = st.number_input("📉 Loan % of Income", min_value=0.0, max_value=1.0, step=0.01)

cb_person_cred_hist_length = st.number_input("📜 Credit History Length (Years)", min_value=0.0, max_value=100.0, step=0.1)
credit_score = st.number_input("📊 Credit Score", min_value=300, max_value=850, step=1)

previous_loan_defaults_on_file = st.selectbox("📂 Previous Loan Defaults?", ["Yes", "No"])

# Predict button
if st.button("🔮 Predict Loan Approval"):
    input_dict = {
        "person_age": person_age,
        "person_gender": person_gender,
        "person_education": person_education,
        "person_income": person_income,
        "person_emp_exp": person_emp_exp,
        "person_home_ownership": person_home_ownership,
        "loan_amnt": loan_amnt,
        "loan_intent": loan_intent,
        "loan_int_rate": loan_int_rate,
        "loan_percent_income": loan_percent_income,
        "cb_person_cred_hist_length": cb_person_cred_hist_length,
        "credit_score": credit_score,
        "previous_loan_defaults_on_file": previous_loan_defaults_on_file
    }

    # Convert to DataFrame
    input_df = pd.DataFrame([input_dict])

    # Predict
    prediction = pipeline.predict(input_df)[0]

    if prediction == 1:
        st.success("✅ Loan Approved!")
    else:
        st.error("❌ Loan Not Approved.")